### ISSUE TITLE
Authentication method 

### ISSUE THREAD

**Issue by frodinm** [PaulL48/SOEN341-SC4#33]
Could we implement a token authentication for our login process? So a system where the server responds with an api token when the user makes a login request. This token would only be valid for 10 mins, and then if the user is still logged in after 10 mins  we refresh the token.

**Comment by frodinm** [comment]
i was looking at this blog post for pointers on how to do this : https://gistlog.co/JacobBennett/090369fbab0b31130b51

**Comment by ACuriousSeaTurtle** [comment]
As discussed in Meeting 5, since there is currently an already a working login system (just without an apparent token) this will be put in the potential backlog for sprint 3. I have an assumption that laravel does in fact create a token and manage it somewhere, but doesn't immediately expose it.

Before acting on this there will be an investigation period to assure that there is in fact no facility in laravel to obtain this token, since creating and maintaining two tokens would be redundant. This investigation can be performed by any member who wants to. Please assign yourself to this issue if you are or will investigate this, and post discussions or findings here.

**Comment by ACuriousSeaTurtle** [comment]
Accidentally closed the issue.

**Comment by ACuriousSeaTurtle** [comment]
Just thinking on this for a bit, the posted blog article looks like it handles API calls that require authentication, which is very important, so disregard my decision of putting this in sprint 3. Sprint 2 seems the better place for this

**Comment by frodinm** [comment]
I managed to make the authentication work with react. The code was missing a hidden text input that input the csrf token with every request. I recommend closing this since an api token login system is no longer necessary.
